upkoding/komunitas

README.md

Disini saya menambahkan data tentang Eka Putra.

Menambahkan info Eka Putra

---

README.md

Adi menambahkan info

---

README.md

Disini saya menambahkan tentang rizky darmawan.
terima kasih mas sangat menginspirasi

Menambahkan profile rizky darmawan

---

README.md

Saya ingin bergabung ke komunitas upkoding dengan ikut menambahkan info Diri

Menambahkan Info Rizal Gente

---

README.md

Halo saya menambahkan info tentang diri saya , Terimakasih sudah membuat video tentang "Cara Berkontribusi Ke Proyek Open Source (Sumber Terbuka) di GitHub"

menambahkan info Giovanni Kurniawan

---

README.md

Pengisian data dan juga sekalian belajar git push,commit,dan lain-lain . Terima Kasih Sebelumnya

isi data diri

---

README.md

I added my profile and github link

added abdoerrahiem's info

---

README.md

saya menambahkan info tentang saya dan link github saya

menambah info M.Hidayatullah

---

README.md

Menambahkan data diri Hasan Ikhtiarta. Terima kasih mas eka putra atas materi di channel UpKoding! sukses terus

join komunitas UpKoding Hasan Ikhtiarta

---

README.md

Saya menambahkan info untuk Rizky Kurniawan.

Menambahkan Info Untuk Rizky Kurniawan

---

README.md

Disini saya menambahkan Informasi singkat diri saya.
saya ucapkan terima kasih pada Mas Eka, semoga saya bisa bekerja di luar negeri juga suatu saat nanti :D

Menambahkan Info Wisnu Prasetio

---

README.md

Perkenalan diri dari Cecep Maulana

Menambahkan info Cecep Maulana

---

README.md

disini saya menambahkan info tentang saya (iksan arifki)

menambahkan info iksan arifki

---

README.md

mimpi saya sudah saya tulis di sini.  doakan saya ya mas dan semuanya. agar saya bisa konsisten bisa menuju goal saya. dan bisa membanggakan semua orang yang kenal saya. amin

Menambahkan info tentang imotD

---

README.md

My first contribute and Pull requests on Github.

Add Info About Billy

---

README.md

Hai , Salam Kenal ikut coba mempraktikan dari content youtube UpKoding Terimakasih

add rohmat assari

---

README.md

Halo mas
Saya telah melakukan pengeditan file pada komunitas anda. saya ingin belajar berkontribusi pada sebuah komunitas opensource. terima kasih mas

menambahkan data Amanudin Harahap

---

README.md

Aku menambahkan info tentang diri saya sendiri

menambahkan info edwin

---

README.md

Adding Umar

---

README.md

halo halo tolong di accept ya bang thank you😁

Menambah Ardhi Putrap profile

---

README.md

Saya sudah menambahkan informasi tentang data Muhamad Hamdanil

Menambahkan Info Muhamad Hamdanil

---

README.md

Berkontribusi ke open source untuk pertama kali, terima kasih banyak mas eka!

Menambahkan data tentang saya dan 

---

README.md

Terima kasih atas tutorialnya, semoga bermanfaat

marwan bergabung

---

README.md

biodata dan profil github, terima kasih.

perkenalan menambah biodata

---

README.md

selesai menambahkan tentang syarif

menambahkan tentang syarif

---

README.md

halo bli @ekaputra07, ada sesuatu hal yang membuat saya dengan terpaksa menghapus informasi "bagian saya" disini, barangkali berkenan, mohon di approve :)

delete my part :)

---

README.md

Perkenalan tentang saya dan apa yang sedang saya pelajari.

Menambahkan Info Muhammad Akmal Irfansyah

---

README.md

Disini saya menambahkan data tentang Marzuki.

Menambahkan info Marzuki

---

README.md

Menambahkan info tentang Arif Siddik Muharam

Menambahkan info tentang Arif Siddik Muharam

---

README.md

halo izin bang
saya menambahkan beberapa info ke ken

menambahkan beberapa info ke ken

---

README.md

Hi @ekaputra07  I hope you agree that I want to delete the info I provided in your repository two years ago. At that time I just wanted to learn and now I understand. Thanks for the knowledge sharing.

menghapus info edwin
